import Head from "next/head";
export default function HeadComponent(props) {
  return (
    <Head>
      <title>{props.title ? props.title : "TRYING NEXT JS"}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
